-- OPTIONAL. Adds a composite index on (day, ref_domain_id).
--
--   wrangler d1 execute <db> --remote --file=migrations/add-referrer-index.sql
--
-- ## CHECK THE WRITE BUDGET FIRST -- this one can drop pageviews
--
-- Building an index writes ONE ROW PER EXISTING TABLE ROW. D1's free tier
-- allows 100,000 rows written per day **account-wide, across every database**,
-- and when that is exhausted writes fail -- which for this worker means ingest
-- starts dropping real pageviews for the rest of the UTC day.
--
--   wrangler d1 info <db>     # read `rows_written_24h` for EVERY database first
--
-- Rule of thumb: only run this if (sum of rows_written_24h across all your
-- databases) + (row count of this events_tab) leaves comfortable headroom under
-- 100K. Run it just after 00:00 UTC, when the quota resets.
--
-- There is also a permanent cost: every index covering an inserted column adds
-- one written row per pageview forever. At 4K pageviews/day that is another
-- 4K writes/day against the same 100K budget.
--
-- ## What it buys
--
-- Nothing on the default dashboard: unfiltered pageview breakdowns are served
-- from dim_daily_tab and never touch events_tab. It only speeds up the raw
-- fallback path -- filtered queries and multi-day metric=visitors -- and only
-- when the filter is on referrer. Worth it on a busy database where people
-- filter by referrer a lot; skip it otherwise.

CREATE INDEX IF NOT EXISTS idx_events_day_ref ON events_tab(day, ref_domain_id);
